# Generated by Django 4.1.7 on 2023-03-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_postcrud_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcrud',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
